#!/usr/bin/env node

/**
 * Convert HTML bundle to JavaScript/TypeScript constant with MD5 hash
 *
 * This allows the survey bundle to be included in the Metro JS bundle
 * instead of being a native asset, enabling:
 * - Hot reload during development
 * - OTA updates via Expo Updates
 * - No native rebuild needed for survey changes
 *
 * The HTML is written to the filesystem on app launch (if needed) and
 * loaded via file:// URL to avoid iOS WebView inline script size limits.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Paths
const htmlPath = path.join(__dirname, '../../native-app/assets/survey/index.html');
const outputPath = path.join(__dirname, '../../native-app/src/generated/surveyBundle.ts');

console.log('[html-to-js] Converting HTML bundle to TypeScript...');
console.log('[html-to-js] Input:', htmlPath);
console.log('[html-to-js] Output:', outputPath);

// Read HTML file
if (!fs.existsSync(htmlPath)) {
  console.error('[html-to-js] ERROR: HTML bundle not found at:', htmlPath);
  console.error('[html-to-js] Did you run the Vite build first?');
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf-8');
const htmlSizeKB = (html.length / 1024).toFixed(2);

console.log('[html-to-js] HTML bundle size:', htmlSizeKB, 'KB');

// Calculate MD5 hash of the HTML
const hash = crypto.createHash('md5').update(html).digest('hex');
console.log('[html-to-js] HTML MD5 hash:', hash);

// Generate TypeScript file
const tsContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: packages/web-app/scripts/html-to-js.js
 * Source: packages/native-app/assets/survey/index.html
 * Size: ${htmlSizeKB} KB
 * MD5 Hash: ${hash}
 * Generated: ${new Date().toISOString()}
 *
 * This file contains the survey HTML bundle for inclusion in the Metro JS bundle.
 * The HTML is written to the filesystem on app launch (if hash doesn't match)
 * and loaded via file:// URL to avoid iOS WKWebView inline script size limits.
 *
 * Allows the survey to be included in the Metro JS bundle for:
 * - Hot reload during development
 * - OTA updates via Expo Updates (no native rebuild needed)
 */

export const SURVEY_HTML = ${JSON.stringify(html)};
export const SURVEY_HTML_MD5 = '${hash}';
export const SURVEY_HTML_SIZE_KB = ${htmlSizeKB};
export const SURVEY_GENERATED_AT = '${new Date().toISOString()}';
`;

// Ensure output directory exists
fs.mkdirSync(path.dirname(outputPath), { recursive: true });

// Write TypeScript file
fs.writeFileSync(outputPath, tsContent, 'utf-8');

console.log('[html-to-js] ✅ Successfully generated:', outputPath);
console.log('[html-to-js] TypeScript file size:', (tsContent.length / 1024).toFixed(2), 'KB');
console.log('[html-to-js] The HTML will be written to filesystem on app launch and loaded via file://');
console.log('[html-to-js] OTA updates will trigger filesystem update when MD5 hash changes');
